name: Release

on:
  release:
    types:
      - released
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  release:
    name: ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            upx_args: --best --lzma
            upx_strip: false
          - target: aarch64-unknown-linux-musl
            upx_args: --best --lzma
            upx_strip: false
          - target: x86_64-unknown-linux-gnu
            upx_args: --best --lzma
            upx_strip: true
          - target: x86_64-unknown-linux-musl
            upx_args: --best --lzma
            upx_strip: true
          - target: aarch64-apple-darwin
            os: macos-latest
            upx_args: --best
            upx_strip: false
          - target: x86_64-apple-darwin
            os: macos-latest
            upx_args: --best
            upx_strip: true
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            upx_args: -9
            upx_strip: false
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.0.2
      - name: Get binary name
        uses: dangdennis/toml-action@v1.3.0
        id: read_cargo_toml
        with:
          file: "Cargo.toml"
          field: "package.name"
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }} --locked
      - name: Compress binaries
        if: endsWith(matrix.target, 'windows-msvc') == false
        uses: svenstaro/upx-action@v2
        with:
          file: target/${{ matrix.target }}/release/${{ steps.read_cargo_toml.outputs.value }}
          args: ${{ matrix.upx_args }}
          strip: ${{ matrix.upx_strip }}
      # we use these artifact later in the docker build to prevent having to rebuild
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
        with:
          name: dd-metric-arm64
          path: target/${{ matrix.target }}/release/${{ steps.read_cargo_toml.outputs.value }}
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        with:
          name: dd-metric-amd64
          path: target/${{ matrix.target }}/release/${{ steps.read_cargo_toml.outputs.value }}
      - uses: taiki-e/upload-rust-binary-action@v1
        if: ${{ github.event_name == 'release' }}
        with:
          bin: ${{ steps.read_cargo_toml.outputs.value }}
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          include: LICENSE,README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-docker:
    name: build-docker-image
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository}}
      - uses: actions/download-artifact@v3
        with:
          name: dd-metric-amd64
          path: dd-metric-amd64
      - uses: actions/download-artifact@v3
        with:
          name: dd-metric-arm64
          path: dd-metric-arm64
      - name: Display structure of downloaded files
        run: ls -R
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
