name: Tests

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.0.2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo fmt
        run: |
          cargo fmt --all --
      - name: Run clippy
        run: |
          cargo clippy --all-targets --all-features -- -Dclippy::all
      - name: Run cargo test
        run: |
          cargo test
      - name: Run cargo-toml-lint
        run: |
          cargo install cargo-toml-lint
          cargo-toml-lint Cargo.toml
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.0
